name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort ruff flake8

      - name: Format code with Black
        run: black .

      - name: Sort imports with isort
        run: isort .

      - name: Fix issues with Ruff
        run: ruff check --fix .

      - name: Commit formatted code
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto-fix with Black, isort & Ruff"

      - name: Lint with Ruff
        run: ruff check .

      - name: Test with pytest
        run: pytest
